package com.inomera.mb.constans;

public class GeneralConstants {

	//public static final String SECURITY_KEY = "WVhCd1ZYSnNQV2gwZEhBbE0wRWxNa1lsTWtadGIySnBMbTVsZEcxbGNtRXVZMjl0SlROQk9EQWxNa1p0YjJKcGJXVnlZU1V5Um1kaFpHZGxkQ1V5Um1odmJXVXVlRzFzSm01dFUybDBaVlZ5YkQxb2RIUndKVE5CSlRKR0pUSkdiVzlpYVM1dVpYUnRaWEpoTG1OdmJTVXpRVGd3Sm0xdlpIVnNaVWxrUFRFME5qVW1ZWEJ3U1dROWJXOWlhVzFsY21FbWJtMVVaVzF3YkdGMFpUMWpiM0p3YjNKaGRHVW1iM2R1WlhKSlpEMXpaSEJmWVdSdGFXNG1aRzl0WVdsdVBXNWxkRzFsY21FdVkyOXRKbTV0VTJsMFpUMXRiMkpwYldWeVlTWnZkMjVsY2xKdmJHVlVlWEJsUFRBbWRtbGxkMlZ5VW05c1pWUjVjR1U5TUNaMmFXVjNaWEpKWkQxelpIQmZZV1J0YVc0bQ==";
	public static final String SECURITY_KEY = "WVhCd1ZYSnNQV2gwZEhBbE0wRWxNa1lsTWtZMU1EY3hNemt5TlM1dVpYUnRaWEpoTG1OdmJTVXpRVGd3SlRKR2JXOWlhVzFsY21FbE1rWm5ZV1JuWlhRbE1rWm9iMjFsTG5odGJDWnViVk5wZEdWVmNtdzlhSFIwY0NVelFTVXlSaVV5UmpVd056RXpPVEkxTG01bGRHMWxjbUV1WTI5dEpUTkJPREFtYlc5a2RXeGxTV1E5TWprek5DWmhjSEJKWkQwMU1EY3hNemt5TlNadWJWUmxiWEJzWVhSbFBXMXZZbWwwWlcxd2JHRjBaU1p2ZDI1bGNrbGtQWEJoY25acGJpMW5ZWE5wYlhwaFpHVW1aRzl0WVdsdVBXNWxkRzFsY21FdVkyOXRKbTV0VTJsMFpUMDFNRGN4TXpreU5TWnZkMjVsY2xKdmJHVlVlWEJsUFRFbWRtbGxkMlZ5VW05c1pWUjVjR1U5TVNaMmFXVjNaWEpKWkQxd1lYSjJhVzR0WjJGemFXMTZZV1JsSmc=";


	public static final String DATA_TABLE_NAME = "mobiBlogger";
	
	public static final String KEY_TITLE = "title";
	public static final String KEY_DESCRIPTION = "description";
	public static final String KEY_PATH = "path";
	public static final String KEY_PHOTOS = "file";
	public static final String KEY_LAT = "latitude";
	public static final String KEY_LONG = "longitude";
}
